#
# Official definition of distinguishedNameMatch
# https://datatracker.ietf.org/doc/html/rfc4517#section-4.2.15
#
import base64
import re
from urllib.parse import unquote, unquote_plus

from cryptography import x509
from cryptography.x509.oid import ObjectIdentifier, NameOID
from cryptography.x509 import load_pem_x509_certificate

# Omissions cryptography's OIDs
# Previous code tried to fix this by using a Mozilla compiled list of OIDs, oids.txt in:
#     https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_12_3_1_RTM/src/nss-3.12.3.1.tar.gz
# but that contained duplicate tags for different OIDs. So we just stick to
# what cryptography knows, with some known ommissions, and be less flexible to
# what the administrator put in the allowed_client_subject_dn_path file.
#
# Example: openssl x509 -nameopt RFC2253 -text output:
#     "CN=University Corporation For Advanced Internet Development,emailAddress=knewell@internet2.edu,organizationIdentifier=NTRUS\\+MI-801069584,O=University Corporation For Advanced Internet Development,ST=Michigan,C=US"
# According to https://datatracker.ietf.org/doc/html/rfc4514#page-7 'emailAddress' is not a MUST,
# nor is 'organizationIdentifier'. cryptography package doesn't do MAY
#
names2oid = {}
names2oid["sn"] = ObjectIdentifier("2.5.4.4")  # surname
names2oid["SN"] = ObjectIdentifier("2.5.4.4")
names2oid["gn"] = ObjectIdentifier("2.5.4.42") # givenname
names2oid["GN"] = ObjectIdentifier("2.5.4.42")
names2oid["organizationIdentifier"] = ObjectIdentifier("2.5.4.97")
names2oid["emailAddress"] = ObjectIdentifier("1.2.840.113549.1.9.1")


def dn_rfc2253_string_to_rfc4514_name(rfc2253_string:str):
    """
        Convert a string with a DistinguishedName in RFC2253 format, such as generated by:
             openssl x509 -nameopt RFC2253 -in bla.pem -text
        into a cryptography.x509.Name object.

        Args:
            rfc2253_string (str): RFC2253 formatted DN.
            According to openssl CN comes first

        Returns:
            cryptography.x509.Name: Parsed version of DN.
        Raises:
            ValueError: If rfc2253_string is not a valid RFC2253 DN.
    """
    # Output is big-to-small sorted
    return x509.Name.from_rfc4514_string(rfc2253_string,names2oid)


def dn_tagvalue_string_to_rfc4514_name(tagvalue_string:str):
    """
        Convert a string in "tag1=value1,tag2=value2" format, that should represent
        a valid DistinguishedName into a cryptography.x509.Name object, if it can be parsed
        by the cryptography code. tags (symbolic names, not oids) are taken from the set
        of valid DN tags as defined by cryptography, with e.g. "organizationIdentifier" added,
        see above.

        Args:
            tagvalue_string (str): comma-separated tag-value DN

        Returns:
            cryptography.x509.Name: Parsed version of DN.
        Raises:
            ValueError: If tagvalue_string is not a valid DN.
    """
    # Handle case when administrator copy-pastes subject DN from openssl x509 -text call
    # but without -nameopt rfc2253. This means extra spaces and no escaped special chars.
    clean_tagvalue_string = confer_parse_tag_pairs(tagvalue_string)

    rfc454_name = dn_rfc2253_string_to_rfc4514_name(clean_tagvalue_string)
    oidlist = []
    # Copy RDNS
    rdns = list(rfc454_name)
    for rdn in rdns:
        oidlist.append(rdn.oid)

    # cryptography does not fix order, so if input was big-to-small this is not fixed automatically
    # note that big-to-small is the internal representation.
    firstoid = oidlist[0]
    lastoid = oidlist[-1]
    bigtosmall = True
    # Heuristic to determine order. These two fields MUST be "recognized"
    # https://datatracker.ietf.org/doc/html/rfc4514#section-3
    if firstoid == NameOID.COMMON_NAME:
        bigtosmall = False
    elif lastoid == NameOID.COUNTRY_NAME:
        bigtosmall = False
    if not bigtosmall:
        rdns.reverse()

    n = x509.Name(rdns)
    return n


# Arno talking to confer.to:
def confer_parse_tag_pairs(input_string):
        r"""
        Parse a string of tag=value pairs with various separators
        (commas, spaces, or both) and normalize to just commas.
        Values are properly escaped according to RFC 4514 in the output.
        Order is preserved.

        RFC 4514 escaping rules for values:
        - Must escape: , + " # < > ; = \
        - Leading/trailing spaces must be escaped
        - Embedded spaces do NOT need escaping

        Input may have mixed or no escaping; output will be consistently
        escaped per RFC 4514.

        Args:
            input_string: String containing tag=value pairs
                          (e.g., "tag1=val+ue1, tag2=val\\,ue2")

        Returns:
            String with tag=value pairs separated only by commas,
            values properly escaped per RFC 4514, order preserved
        """
        import re

        def unescape_value(value):
            """
            Unescape RFC 4514 escaped sequences in a value.
            Converts \\X back to X for escaped characters.
            """
            result = []
            i = 0
            while i < len(value):
                if value[i] == '\\' and i + 1 < len(value):
                    # Escaped character - take the next char literally
                    result.append(value[i + 1])
                    i += 2
                else:
                    result.append(value[i])
                    i += 1
            return ''.join(result)

        def escape_rfc4514(value):
            """
            Escape a value according to RFC 4514 section 2.4.

            Characters that must be escaped with backslash:
            - Special chars: , + " # < > ; = \
            - Leading space (if first char)
            - Trailing space (if last char)
            """
            if not value:
                return value

            # Characters that always need escaping
            special_chars = {
                ',': '\\,',
                '+': '\\+',
                '"': '\\"',
                '#': '\\#',
                '<': '\\<',
                '>': '\\>',
                ';': '\\;',
                '=': '\\=',
                '\\': '\\\\',
            }

            result = []
            for i, char in enumerate(value):
                if char in special_chars:
                    result.append(special_chars[char])
                elif char == ' ':
                    # Space: only escape if leading or trailing
                    if i == 0 or i == len(value) - 1:
                        result.append('\\ ')
                    else:
                        result.append(char)
                else:
                    result.append(char)

            return ''.join(result)

        input_string = input_string.strip()

        if not input_string:
            return ""

        # Pattern to match tag=value pairs
        # Tag: one or more chars that aren't whitespace, comma, or equals
        # Value: escaped chars (\\.) OR any char except equals, comma, backslash
        pattern = r'([^\s,=]+)=((?:\\.|[^=,\\])*)(?=\s*,?\s*[^\s,=]+=|$)'

        matches = re.findall(pattern, input_string, re.DOTALL)

        if not matches:
            return input_string

        # Unescape input values, then re-escape per RFC 4514. A value beginning
        # with an unescaped '#' is the RFC 4514 hexstring form (e.g. Envoy emits
        # organizationIdentifier as 2.5.4.97=#130E...): pass it through verbatim,
        # else escape_rfc4514 would escape the leading '#' and turn the BER-hex
        # value into a literal string that never decodes.
        result = ','.join(
            f'{tag}={value if value.startswith("#") else escape_rfc4514(unescape_value(value))}'
            for tag, value in matches
        )

        return result
#EOAI


# BER tags for the string types that appear in X.509 DirectoryString-like fields,
# where one input byte maps to one Unicode codepoint (so cryptography's
# str-via-Latin-1 storage round-trips losslessly via codepoint-level operations).
_BER_DIRECTORY_STRING_TAGS = frozenset({
    0x0C,  # UTF8String
    0x13,  # PrintableString
    0x14,  # TeletexString (T.61)
    0x16,  # IA5String
    0x1A,  # VisibleString / ISO646String
})


def _strip_ber_tlv(value: str) -> str:
    """Strip BER TLV framing from `value` if present, else return unchanged.

    Cryptography's `from_rfc4514_string` parser handles the RFC 4514 `#hexstring`
    alternative form for attribute values by storing the raw BER bytes as a str
    (one codepoint per byte). Go's `cert.Subject.String()` emits unrecognized
    attribute types in this form, so a value like `2.5.4.42=#130448616e73`
    becomes `(OID 2.5.4.42, '\\x13\\x04Hans')` — same identity as `GN=Hans` but
    different `.value`. This helper undoes the BER framing for the common
    DirectoryString tags so canonical equality holds.
    """
    if len(value) < 2:
        return value
    tag = ord(value[0])
    if tag not in _BER_DIRECTORY_STRING_TAGS:
        return value
    length_byte = ord(value[1])
    if length_byte & 0x80:
        n = length_byte & 0x7F
        if n == 0 or len(value) < 2 + n:
            return value
        length = sum(ord(value[2 + i]) << (8 * (n - 1 - i)) for i in range(n))
        offset = 2 + n
    else:
        length = length_byte
        offset = 2
    if offset + length != len(value):
        return value
    return value[offset:]


def _value_str(value: str | bytes) -> str:
    """Coerce a NameAttribute value to a canonical str, stripping any BER framing."""
    match value:
        case str():
            return _strip_ber_tlv(value)
        case bytes():
            return _strip_ber_tlv(value.decode("latin-1"))


def name_rfc4514_string(name: x509.Name) -> str:
    """Return the RFC 4514 string of `name` with BER-framed values normalised.

    The default `Name.rfc4514_string()` emits raw bytes for attributes that were parsed
    from the `#hexstring` form, including the low control bytes (0x13 PrintableString
    tag, length prefix, …) at the start of the value. HTTP header values forbid bytes
    below 0x20, so passing that string through `X-Client-DN` makes uvicorn reject the
    response. Rebuilding the Name with `_value_str` applied to every attribute strips
    the BER framing and yields a header-safe representation that preserves the
    original RDN ordering.
    """
    return x509.Name(
        [x509.NameAttribute(a.oid, _value_str(a.value)) for rdn in name.rdns for a in rdn]
    ).rfc4514_string()


def name_attrs(name: x509.Name) -> frozenset[tuple[str, str]]:
    """Return the (OID, value) multiset of a Name.

    Comparing two names by their `name_attrs` is order-independent and
    serialization-independent: identities differing only in RDN order, in
    whether attributes are written with friendly names (`CN=`, `GN=`, …) or
    dotted OIDs (`2.5.4.3=`, `2.5.4.42=`, …), or in whether attribute values
    use the plain form (`=value`) or the RFC 4514 BER hex form (`=#hexstring`)
    compare equal.
    """
    return frozenset(
        (a.oid.dotted_string, _value_str(a.value)) for rdn in name.rdns for a in rdn
    )


def subject_dn_from_cert_pem(cert_pem_bytes:str):
    """
    Parse Subject DN from a PEM-encoded certificate.
    Args:
        cert_pem_str (bytes): PEM framed as per cryptography's rules
        See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file

    Returns:
        cryptography.x509.Name: Parsed version of Subject DN.
    Raises:
        ValueError: If cert_pem_str is not a valid PEM-encoded x.509 certificate.
    """
    cert_obj = load_pem_x509_certificate(cert_pem_bytes)
    subject_name = x509.Name(cert_obj.subject)
    return subject_name


def subject_dn_from_pem_header(header_value: str):
    """Extract the Subject DN from a standard PEM certificate carried in a header.

    HTTP headers cannot contain newlines, so a full PEM is normally URL-encoded
    (e.g. nginx's ``$ssl_client_escaped_cert``). URL-decode first, then parse; a
    value without percent-escapes passes through unchanged.
    """
    return subject_dn_from_cert_pem(bytes(unquote(header_value), "iso-8859-1"))


def subject_dn_from_traefik_cert_pem(traefik_cert_str):
    """Convert Traefik's minimized, HTTP-header-safe PEM to a Subject DN.

    Traefik strips the PEM delimiters and newlines, and separates a chain with
    commas (the client certificate first). Reassemble the first certificate into
    a PEM that cryptography accepts and read its subject.
    See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file
    """
    # Undocumented but consistent across Traefik versions: client cert is first.
    first = next((part.strip() for part in traefik_cert_str.split(",") if part.strip()), "")
    body = "\n".join(first[i:i + 64] for i in range(0, len(first), 64))
    pem = f"-----BEGIN CERTIFICATE-----\n{body}\n-----END CERTIFICATE-----\n"
    # RFC 9110 says header values are opaque bytes; Python can't, so use the
    # legacy HTTP/1.1 header encoding (iso-8859-1).
    return subject_dn_from_cert_pem(bytes(pem, "iso-8859-1"))


def subject_dn_from_traefik_cert_info(header_value: str) -> str | None:
    """Extract DN from Traefik's X-Forwarded-Tls-Client-Cert-Info header.

    Traefik format: Subject="CN=...,O=...,C=..."
    Returns the DN string without the Subject="" wrapper, or None if not found.
    """
    # Arno: See e.g. https://github.com/traefik/traefik/issues/12887
    # Karl: Match Subject="..." pattern and extract the DN
    # Traefik URL-encodes the header value, so decode it first
    match = re.search(r'Subject="([^"]+)"', unquote_plus(header_value))
    if match:
        info_subject_str = match.group(1)
        # The format of the Subject field is controlled by the Traefik administrator,
        # see above. So do flex parsing:
        return dn_tagvalue_string_to_rfc4514_name(info_subject_str)
    return None


def _xfcc_field(header_value: str, key: str) -> str | None:
    """Return the value of one Envoy XFCC field, or None if absent.

    XFCC (``x-forwarded-client-cert``) is ``Key=Value;Key="Quoted value";...``.
    Quoted values (Subject, Cert, Chain) may contain ``;`` and ``=``; match
    case-insensitively and prefer the quoted content.
    """
    match = re.search(
        rf'(?:^|;)\s*{re.escape(key)}=("([^"]*)"|[^;]*)', header_value, re.IGNORECASE
    )
    if not match:
        return None
    return match.group(2) if match.group(2) is not None else match.group(1)


def subject_dn_from_xfcc_cert(header_value: str):
    """Extract the Subject DN from the ``Cert=`` field of an Envoy XFCC header.

    Envoy emits the client certificate as a URL-encoded PEM in ``Cert="..."``
    when ``set_current_client_cert_details.cert`` is true. Returns None if the
    field is absent — there is deliberately no fallback to ``Subject=``.
    """
    cert_field = _xfcc_field(header_value, "Cert")
    if not cert_field:
        return None
    return subject_dn_from_cert_pem(bytes(unquote(cert_field), "iso-8859-1"))


def subject_dn_from_xfcc_subject(header_value: str):
    """Extract the Subject DN from the ``Subject=`` field of an Envoy XFCC header.

    Envoy emits the subject DN (RFC 2253, comma-separated) in ``Subject="..."``
    when ``set_current_client_cert_details.subject`` is true. Returns None if the
    field is absent — there is deliberately no fallback to ``Cert=``.
    """
    subject_field = _xfcc_field(header_value, "Subject")
    if not subject_field:
        return None
    return dn_tagvalue_string_to_rfc4514_name(subject_field)
